[workspace]
members = ["macros"]

[package]
name = "compile-symbol"
version = "0.1.0"
edition = "2021"
authors = ["sam0x17"]
description = "Provides compile-time globally unique, 25-character, 128-bit symbols similar to the Symbol type in Crystal Lang."
keywords = ["symbol", "compile-time", "crystal", "macro", "unique"]
license = "MIT"

[dependencies]
compile-symbol-macros = { path = "macros", version = "0.1.0" }
