[package]
name = "compile-symbol-macros"
version = "0.1.2"
edition = "2021"
authors = ["sam0x17"]
license = "MIT"
description = "support macros for compile-symbol"
repository = "https://github.com/sam0x17/compile-symbol"
homepage = "https://sam0x17.dev"

[lib]
proc-macro = true

[dependencies]
docify = "0.1"
